#ifndef	GLBG_VERSION_INCLUDED
#define GLBG_VERSION_INCLUDED

#define GLBG_MAKE_STR_HELPER(x) #x
#define GLBG_MAKE_STR(x) GLBG_MAKE_STR_HELPER(x)

#define GLBG_VERSION_MAJOR		1
#define GLBG_VERSION_MINOR		3
#define GLBG_VERSION_PATCH		2
#define GLBG_VERSION_BETA		0
#define GLBG_VERSION_VERSTRING	GLBG_MAKE_STR(GLBG_VERSION_MAJOR) "." GLBG_MAKE_STR(GLBG_VERSION_MINOR) "." GLBG_MAKE_STR(GLBG_VERSION_PATCH) "." GLBG_MAKE_STR(GLBG_VERSION_BETA)

#endif
