#ifndef	GLOWBEGONESSE_VERSION_INCLUDED
#define GLOWBEGONESSE_VERSION_INCLUDED

#define GLOWBEGONESSE_MAKE_STR_HELPER(x) #x
#define GLOWBEGONESSE_MAKE_STR(x) GLOWBEGONESSE_MAKE_STR_HELPER(x)

#define GLOWBEGONESSE_VERSION_MAJOR		1
#define GLOWBEGONESSE_VERSION_MINOR		1
#define GLOWBEGONESSE_VERSION_PATCH		0
#define GLOWBEGONESSE_VERSION_BETA		0
#define GLOWBEGONESSE_VERSION_VERSTRING	GLOWBEGONESSE_MAKE_STR(GLOWBEGONESSE_VERSION_MAJOR) "." GLOWBEGONESSE_MAKE_STR(GLOWBEGONESSE_VERSION_MINOR) "." GLOWBEGONESSE_MAKE_STR(GLOWBEGONESSE_VERSION_PATCH) "." GLOWBEGONESSE_MAKE_STR(GLOWBEGONESSE_VERSION_BETA)

#endif
